Implementing support for async_std types
RazrFalcon/memmap2-rs pull request #26
Opened 2021-09-16 13:16 UTC by gabrik

This PR contains the code for supporting `async_std` types in `MmapOptions`.

The `async_std` support is gated using a feature.
If someone wants to use this feature has to enable it in their `Cargo.toml`

eg.
```toml
memmap2 = {version = "0.3.1", features = ["async"] }
```

I tested it on this crate: https://github.com/atolab/zenoh-cdn/tree/feat/all-async

I had no possibility yet to test it on a Windows machine

2021-09-16 18:50 UTC, RazrFalcon requested changes

2021-09-16 18:50 UTC, RazrFalcon commented on Cargo.toml
> +
I think `version = "1"` should be preferred. This way it's up to the caller to choose the specific version.

2021-09-16 18:50 UTC, RazrFalcon commented on Cargo.toml
> +
Needless newline.

2021-09-16 18:50 UTC, RazrFalcon commented on Cargo.toml
> +
Needless newline.

2021-09-16 18:50 UTC, RazrFalcon commented on Cargo.toml
> +default = []
Missing newline.

2021-09-16 18:50 UTC, RazrFalcon commented on Cargo.toml
> +
`default` should be first.

2021-09-16 18:50 UTC, RazrFalcon commented on src/lib.rs
> +
Needless whitespaces.

2021-09-16 18:51 UTC, RazrFalcon commented
Can you also write tests? I guess they should be implemented as a separate crate or example or something. I'm not familiar with async at all.

2021-09-17 13:29 UTC, gabrik commented on Cargo.toml
> +doctest = false
This was added to avoid testing the documentation examples.
When testing the `async` feature the documentation examples fails, this is why I disabled it.

2021-09-19 11:54 UTC, RazrFalcon commented
CI fails.

2021-09-19 12:08 UTC, adamreichold commented
Is it really necessary to special case this for the types from `async_std`? Can't this be achieved by going through raw file descriptors resp. handles without direct coupling between the crates?

Related to that, the use of the feature does seem problematic, e.g.
```
#[cfg(feature = "async")]
#[cfg(windows)]
pub struct MmapRawDescriptor(async_std::os::windows::io::RawHandle);

#[cfg(not(feature = "async"))]
#[cfg(windows)]
pub struct MmapRawDescriptor<'a>(&'a File);
```
seems to imply that if any crate in the dependency tree enable the `async` feature, this crate will loose its support for `std::fs::File`? What if there are users of this crate which depend on the `std`-based API? Features should generally be additive, i.e. in this case add implementations of `MmapAsRawDesc` but not remove them.

2021-09-19 12:13 UTC, RazrFalcon commented
Agree. I would prefer the integration of this feature to be more simple.

2021-09-19 15:32 UTC, RazrFalcon commented
Superseded by #31

2021-09-19 15:32 UTC, closed without merging