add map_copy_read_only
RazrFalcon/memmap2-rs pull request #4
Opened 2020-12-14 20:59 UTC by zserik

see also: https://github.com/danburkert/memmap-rs/pull/82

2020-12-14 21:08 UTC, RazrFalcon requested changes

2020-12-14 21:08 UTC, RazrFalcon commented on src/lib.rs
> +    #[inline]
We don't need it.

2020-12-14 21:08 UTC, RazrFalcon commented on src/lib.rs
> +/// Wraps an `MmapInner` struct inside of a `Mmap` struct. Helper function.
Move any unrelated changes to a separate pull request.

2020-12-14 21:13 UTC, RazrFalcon approved these changes

2020-12-16 00:03 UTC, RazrFalcon commented
Can you force-push to restart the CI?

2020-12-16 06:48 UTC, zserik commented
Done.

2020-12-16 13:26 UTC, merged